### ISSUE TITLE
Payment button bug

### ISSUE THREAD

**Issue by Lolcsi** [paylike/plugin-prestashop-1.7#21]
Hi,

I found a bug. If I not checked terms and condition box on order page and just clicking the paylike button appear the paylike overlay. Attached picture this bug.
![paylike term codition bug](https://user-images.githubusercontent.com/23224558/90640674-8e2f6600-e230-11ea-96c8-09b029ea0f7d.jpg)

I use Prestashop 1.7.6.7, PHP 7.2 and default prestashop step by step checkout.

Best Regards

**Comment by cosminbosutar** [comment]
Hello @Lolcsi,

Thank you for sharing this!

If I understand correctly, the problem is that the payment popup is displayed when the "Terms and Conditions" checkbox is not checked and you expect for this not to be possible.

Did I understand correctly?
Can you please confirm?

Thank you!
Cosmin

**Comment by Lolcsi** [comment]
Hi @cosminbosutar 

Yes your understand my problem.

Thx

**Comment by cosminbosutar** [comment]
Hello @Lolcsi,

I was not able to reproduce the bug you mentioned.

Can you please confirm that you are using the latest version of the plugin?

There is also the following intended and expected behavior:
1. In order to unlock the "Pay" button and make the payment popup appear you first need to check the "Terms and Conditions" checkbox;
2. After the payment popup is displayed, the "Terms and Conditions" checkbox is automatically unchecked;
    - This is an intended behavior that forces the user to check again the "Terms and Conditions" checkbox only if he/she wants to open the payment popup again.

Can you please test the above scenario?

Thank you!
Cosmin

**Comment by Lolcsi** [comment]
Hi @cosminbosutar 

I have 1.0.8 paylike version. I understand but not need to check "Terms and Conditions" checkbox because I simply clicking  "Pay" button and appear payment popup.

![captured](https://user-images.githubusercontent.com/23224558/91056104-d3cfa280-e625-11ea-97ad-9c387bbbf07e.gif)

Best Regards
Lolcsi

**Comment by cosminbosutar** [comment]
Hello @Lolcsi,

You are correct, I managed to reproduce the bug. The first test I did was with an older version of the plugin.

It seems that the bug was introduced as a regression in version 1.0.7, when support for one-page checkout was developed. 

We are currently working on the fix.

As a temporary fix please rollback to version 1.0.6 and we will inform you when a new version of the plugin that includes the fix is available.

Does this work for you @Lolcsi?

Thank you!
Cosmin

**Comment by Lolcsi** [comment]
Hi @cosminbosutar 

Sorry for late reply. For now I stay 1.0.8 version

THX

**Comment by ionutcalara** [comment]
Hi @Lolcsi the latest update (1.0.9) fixes this issue. Let us know if encounter any issues.
