### ISSUE TITLE
Refund in backoffice not working

### ISSUE THREAD

**Issue by Lolcsi** [paylike/plugin-prestashop-1.7#32]
Hi,

I've got this error after clicked "Process Action" button and then nothing happens.
Any ideas?
My PS version 1.7.7.2
![action](https://user-images.githubusercontent.com/23224558/117460570-f3f18880-af4c-11eb-8f9d-b23d9b388bcd.jpg)

**Comment by cosminbosutar** [comment]
Hello @Lolcsi,

Thank you for reporting this.

The problem is due to the fact that the plugin is not 100% compatible with the newest PS 1.7 versions.

We are aware of this and we are very close to releasing un update that solves the above issue.

I'll come back after the new version is released.

Thank you!
Cosmin Bosutar

**Comment by Lolcsi** [comment]
Hi @cosminbosutar,

That's right. Attached picture is the refund page? If yes,  I checked paylike checkbox but doesn't work.
![refund](https://user-images.githubusercontent.com/23224558/117834034-2239d580-b277-11eb-8f9d-8d84af70dc70.jpg)

**Comment by Lolcsi** [comment]
Hi @cosminbosutar,

I do everything the same way you do but refund not working. I tried cancel order and partial refund.

**Comment by cosminbosutar** [comment]
Hello @Lolcsi,

PS 1.7.7.3 was used during development and PS 1.7.7.4 during testing.

We will test on PS 1.7.7.2 to check if there are any compatibility issue.

Could you upgrade to 1.7.7.3 or 1.7.7.4?

Thank you!
Cosmin Bosutar

**Comment by Lolcsi** [comment]
Hi @cosminbosutar,

1.7.7.2 not worked after I upgrade 1.7.7.4. result is same

**Comment by cosminbosutar** [comment]
Hello @Lolcsi,

It seems that the problem is environment specific and in this case we would need access to you shop.

Can you please reach out to support [https://paylike.io/contact](https://paylike.io/contact) and mention this ticket so that we can get access to the shop as well?

I think this is the only way we can get to the bottom of this, as this looks very to the environment.

Thank you!
Cosmin Bosutar

**Comment by cosminbosutar** [comment]
Hello @Lolcsi,

The credentials you provided over the ticketing system don't work.

Can you please check the credentials and send the again?

Thank you!
Cosmin Bosutar

**Comment by Lolcsi** [comment]
Hi Cosmin,

I'm sorry, it's my fault.
Now it works.

Best Regards
Lolcsi

genuineq ***@***.***> ezt írta (időpont: 2021. jún. 10., Cs,
10:33):

**Comment by cosminbosutar** [comment]
Hello again @Lolcsi,

The credentials now work.

We performed a test and we managed to reproduce the mentioned error.

From the test we performed it seems that you are not using the latest version of the plugin.

Could you provide us with FTP access as well?
Or can you please send over a copy of the installed plugin?

Please send any credentials ONLY in the ticketing system.

Thank you!
Cosmin Bosutar

**Comment by cosminbosutar** [comment]
Hello @Lolcsi,

We solved the problem.

The issue was that that hooks from the Paylike plugin were not initialized because there was a conflict with the "Admin menu manager" module.

The fix was to deactivate the "Admin menu manager" module, reinstall the Paylike module and reactivate the "Admin menu manager" module.

Can you please test?

Thank you!
Cosmin Bosutar

**Comment by ionutcalara** [comment]
Hi @Lolcsi, due to the lack of response we are going to close the ticket, but feel free to reopen if you still have issues.

Thank you, 
Ionut
